wip: create Collect Cards guide
Basis-Theory/developers.basistheory.com pull request #102
Opened 2023-04-12 19:08 UTC by djejaquino

## Description

-

## Testing required outside of automated testing?

- [ ] Not Applicable

### Screenshots (if appropriate):

- [ ] Not Applicable

## Rollback / Rollforward Procedure

- [ ] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2023-04-17 18:49 UTC, armsteadj1 requested changes

2023-04-17 18:49 UTC, armsteadj1 commented on docs/guides/collect/collect-cards.mdx
> +When building an e-commerce application, subscription service, or enabling one-time purchases, one of the critical requirements is collecting and storing cardholder data securely. However, it can be
```suggestion
When building an e-commerce application, subscription service, or enabling one-time purchases, one of the critical requirements is collecting and storing cardholder data securely. However, it can be challenging to navigate the PCI DSS and ensure that your application meets all the necessary security controls required to comply.
```

2023-04-17 18:49 UTC, armsteadj1 commented on docs/guides/collect/collect-cards.mdx
> +In this guide, we will set up SDKs to capture cards in the frontend, Web or Mobile, and securely store the cardholder data as tokens with the Basis Theory Platform. Given it is followed as it is, you
```suggestion
In this guide, we will use Basis Theory SDKs to capture cards in a frontend application, Web or Mobile, and securely store the cardholder data as tokens with the Basis Theory Platform. Given this guide is followed step by step, your applications, systems, and databases are removed from 95% of PCI compliance scope.
```

2023-04-17 18:49 UTC, armsteadj1 commented on docs/guides/collect/collect-cards.mdx
> +In this guide, we will set up SDKs to capture cards in the frontend, Web or Mobile, and securely store the cardholder data as tokens with the Basis Theory Platform. Given it is followed as it is, you
we probably want to be a bit careful using "completely" in the future as well. The intent behind the statement is right, although could be construed differently legally.

2023-04-17 18:49 UTC, armsteadj1 commented on docs/guides/collect/collect-cards.mdx
> +Once properly installed and configured, add the Card Elements to your application. This will enable users to type in their card data in your form, while refraining from your systems to come in contac
```suggestion
Once installed and configured, please add the Card Elements to your application. This will enable your users to type in their card data in your form while ensuring your systems never come in contact with the data.
```

2023-04-17 18:49 UTC, armsteadj1 commented on docs/guides/collect/collect-cards.mdx
> +To do this, we will call the [Create Token](https://developers.basistheory.com/docs/api/tokens/#create-token) endpoint from the SDK, passing the Card Elements as data points in the payload. This way,
```suggestion
To do this, we will create a token with the [Create Token](https://developers.basistheory.com/docs/api/tokens/#create-token) endpoint from the SDK, passing the Card Elements as data points in the payload. This will securely create a token by transferring the card information from the frontend Elements to Basis Theory, where the card will be strongly encrypted and stored in a compliant environment.
```

2023-04-17 18:49 UTC, armsteadj1 commented on docs/guides/collect/collect-cards.mdx
> +By leveraging [token fingerprinting](/docs/concepts/what-are-tokens#fingerprinting), developers can recognize the tokenized data in a customizable fashion, without having to come in contact with the
```suggestion
By leveraging [token fingerprinting](/docs/concepts/what-are-tokens#fingerprinting), developers can recognize the tokenized data in a customizable fashion, without having to come in contact with the plaintext data. For cards, it is common to index in the Primary Account Number (PAN), in some cases the expiration date may also be considered.
```

2023-04-17 18:49 UTC, armsteadj1 commented on docs/guides/collect/collect-cards.mdx
> +When a card token is created, the returned data follows a default masking pattern that reveals the last 4 digits of card. This is useful for displaying the card to the end-user without revealing the
```suggestion
By default Card token's are created with a mask revealing only the last 4 digits of the card number. This is useful for generating receipts and payment history, etc which display the card details to the end-user without revealing the full number.
```

2023-04-17 18:49 UTC, armsteadj1 commented on docs/guides/collect/collect-cards.mdx
> +However, being able to preserve the Bank Identification Number (BIN) from the card number can also be required for several reasons, including fraud detection, payment processing, customer service or
```suggestion
In other scenarios, being able to preserve the Bank Identification Number (BIN) from the card number can enable fraud detection, payment processing, customer service or account management. [PCI DSS allows](https://www.pcisecuritystandards.org/faq/articles/Frequently_Asked_Question/What-are-acceptable-formats-for-truncation-of-primary-account-numbers/) applications to reveal up to the first 8 and last 4 digits of a card number, depending on its length and Payment Brand. Luckily, when creating a token, you can express what segments of the PAN are useful to you with a single expressions filter: `card_mask`.
```

2023-04-17 18:49 UTC, armsteadj1 commented on docs/guides/collect/collect-cards.mdx
> +By following the best practices prescribed in this guide, you can ensure that your user-facing applications are compliant with the latest security standards while protecting your users' sensitive car
```suggestion
The following best practices prescribed in this guide ensure that user-facing applications are compliant with the PCI-DSS standards and also ensure users' card data is protected. The `token.id` obtained at the end of the [Storing Cards](#storing-cards) section is a synthetic replacement for the sensitive data and can be safely stored in your database, or transmitted through your systems, meeting compliance requirements and reducing the risk of exposure.
```

2023-04-17 18:51 UTC, djejaquino commented on docs/guides/collect/collect-cards.mdx
> +When building an e-commerce application, subscription service, or enabling one-time purchases, one of the critical requirements is collecting and storing cardholder data securely. However, it can be
"the PCI DSS" or just "PCI DSS"?

2023-04-17 18:53 UTC, djejaquino commented on docs/guides/collect/collect-cards.mdx
> +In this guide, we will set up SDKs to capture cards in the frontend, Web or Mobile, and securely store the cardholder data as tokens with the Basis Theory Platform. Given it is followed as it is, you
I noticed that too in other spots in our documentation. Felt like previous author had went through the scrutiny for using that language. I agree with this though.

2023-04-17 18:54 UTC, djejaquino commented on docs/guides/collect/collect-cards.mdx
> +Once properly installed and configured, add the Card Elements to your application. This will enable users to type in their card data in your form, while refraining from your systems to come in contac
I find it common to use imperative language on guides, without the need of words like "please", "kindly", etc. The rest of the suggestions will be taken though.

2023-04-17 19:38 UTC, djejaquino commented on docs/guides/collect/collect-cards.mdx
> +In this guide, we will set up SDKs to capture cards in the frontend, Web or Mobile, and securely store the cardholder data as tokens with the Basis Theory Platform. Given it is followed as it is, you
> your applications, systems, and databases
Can we say all that based on this single guide though?

2023-04-17 20:46 UTC, armsteadj1 commented on docs/guides/collect/collect-cards.mdx
> +In this guide, we will set up SDKs to capture cards in the frontend, Web or Mobile, and securely store the cardholder data as tokens with the Basis Theory Platform. Given it is followed as it is, you
> I noticed that too in other spots in our documentation. Felt like previous authors went through the scrutiny for using that language. I agree with this though.

Yea, we should revisit all of the other guides for this type of statement as well. I'll take it back to Jin to make sure, although "completely" isn't accurate unfortunately

2023-04-17 20:47 UTC, brigonzalez commented on docs/guides/collect/collect-cards.mdx
> +        BasisTheoryElements.tokenize(body: body, apiKey: config.btApiKey!) { token, error in
```suggestion
        BasisTheoryElements.tokenize(body: body, apiKey: "test_1234567890") { token, error in
```
doesn't look like `config` is defined here. but you could replace this with the plaintext API key

2023-04-17 20:47 UTC, armsteadj1 commented on docs/guides/collect/collect-cards.mdx
> +In this guide, we will set up SDKs to capture cards in the frontend, Web or Mobile, and securely store the cardholder data as tokens with the Basis Theory Platform. Given it is followed as it is, you
> your applications, systems, and databases

> Can we say all that based on this single guide though?

I added "..scope when collecting cards." to the end of that sentence. Do you think that makes sense? Basically just saying, for this specific use-case we remove 95% of the requirements.

if not, we could probably write it a bit more generic and say "overall we reduce 95% and this is once step of that" 🤷🏻‍♂️

2023-04-17 20:48 UTC, brigonzalez commented on docs/guides/collect/collect-cards.mdx
> +        BasisTheoryElements.tokenize(body: body, apiKey: config.btApiKey!) { token, error in
```suggestion
        BasisTheoryElements.tokenize(body: body, apiKey: "test_1234567890") { token, error in
```

2023-04-17 20:55 UTC, djejaquino commented on docs/guides/collect/collect-cards.mdx
> +        BasisTheoryElements.tokenize(body: body, apiKey: config.btApiKey!) { token, error in
I copied from [here](https://developers.basistheory.com/docs/sdks/mobile/ios/types#collecting-card-data-example). Should we update it as well?

2023-04-17 20:57 UTC, brigonzalez commented on docs/guides/collect/collect-cards.mdx
> +        BasisTheoryElements.tokenize(body: body, apiKey: config.btApiKey!) { token, error in
yeah, definitely. looks like that slipped in!

2023-04-17 21:00 UTC, lcschy commented on docs/guides/collect/collect-cards.mdx
> +        onChange={({ cardBrand }) => setCardBrand(cardBrand)}
I thought we fixed this but the linter gets mad about this w/ me?
We'd need to add `import { Brand } from "@basis-theory/basis-theory-react/types";` and cast `Brand` on:
`const [cardBrand, setCardBrand] = useState<Brand>();`

2023-04-17 21:03 UTC, lcschy commented on docs/guides/collect/collect-cards.mdx
> +      const token = await bt.tokens.create({
```suggestion
      const token = await bt?.tokens.create({
```

Same as before, linter may complain `bt` can be possibly undefined

2023-04-17 21:04 UTC, lcschy commented on docs/guides/collect/collect-cards.mdx
> +          expiration_month: cardExpirationRef.month(),
And here, linter will complain about this methods if we don't cast the interface types. Its up to you though.
I don't think its a big deal personally and wouldn't mind, but depends on the person I guess

2023-04-17 21:07 UTC, lcschy commented on docs/guides/collect/collect-cards.mdx
> +          expiration_month: cardExpirationRef.month(),
Actually I think it does matter, it may say its not a function because it inherits the React ref type.

2023-04-17 21:09 UTC, djejaquino commented on docs/guides/collect/collect-cards.mdx
> +        BasisTheoryElements.tokenize(body: body, apiKey: config.btApiKey!) { token, error in
What is the recommendation for injecting configuration of such sensitive data? When I copied that I kind of was assuming that the `config.btApiKey` was a standard people would recognize.

2023-04-17 21:09 UTC, lcschy commented on docs/guides/collect/collect-cards.mdx
> +          expiration_month: cardExpirationRef.month(),
```suggestion
          expiration_month: cardExpirationRef.current.month(),
```

2023-04-17 21:10 UTC, lcschy commented on docs/guides/collect/collect-cards.mdx
> +          expiration_year: cardExpirationRef.year(),
```suggestion
          expiration_year: cardExpirationRef.current.year(),
```

2023-04-17 21:16 UTC, brigonzalez commented on docs/guides/collect/collect-cards.mdx
> +        BasisTheoryElements.tokenize(body: body, apiKey: config.btApiKey!) { token, error in
sorry about that. I may have added to the confusion here. that config is something we created so that we wouldn't have to leak our own test API keys from our public repo. in general, because an iOS app is something that is purely client side where you could inspect traffic or decompile the app (more involved with iOS but straightforward with Android) it's normal to treat everything on an iOS app as public. similar to all the client side code we use for elements

2023-04-18 12:37 UTC, djejaquino commented on docs/guides/collect/collect-cards.mdx
> +        BasisTheoryElements.tokenize(body: body, apiKey: config.btApiKey!) { token, error in
Got it. Thank you for the detailed explanation.

2023-04-18 12:58 UTC, djejaquino commented on docs/guides/collect/collect-cards.mdx
> +        onChange={({ cardBrand }) => setCardBrand(cardBrand)}
Let's go with JS on this guide and add more Typescript examples in React documentation

2023-04-18 14:44 UTC, kevinperaza commented on package.json
> +    "@docusaurus/theme-mermaid": "^2.4.0",
I saw you added an `<img>` that links to a mermaid diagram, are any of these mermaid-related updates still required?

2023-04-18 16:38 UTC, djejaquino commented on package.json
> +    "@docusaurus/theme-mermaid": "^2.4.0",
Yes. Will keep the Mermaid setup in case we go back to embedding it directly.

2023-04-18 18:05 UTC, kevinperaza approved these changes

2023-04-18 18:34 UTC, jleon15 commented on src/components/docs/_configure-elements-section.mdx
> +[Basis Theory Elements](/docs/concepts/elements) is available for the following technologies. Click below for detailed instructions on how to install and configure it.
```suggestion
[Basis Theory Elements](/docs/concepts/elements) are available on the following technologies. Click below for detailed instructions on how to install and configure them.
```

2023-04-18 18:36 UTC, jleon15 commented on docs/guides/collect/collect-cards.mdx
> +Once installed and configured, add the Card Elements to your application. This will enable your users to type in their card data in your form, while ensuring your systems never come in contact with t
```suggestion
Once installed and configured, add the Card Elements to your application. This will enable your users to type in their card data in your form, while ensuring your systems never touch the data.
```

2023-04-18 18:38 UTC, jleon15 commented on docs/guides/collect/collect-cards.mdx
> +https://basistheory.com/contact
having the link show up looks weird

2023-04-18 18:44 UTC, jleon15 commented on docs/guides/collect/collect-cards.mdx
> +Notice how the card `number`, also known as Primary Account Number (PAN), has been masked before it is returned to your application. This default behavior prevents your application being pulled in PC
```suggestion
Notice how the card `number`, also known as Primary Account Number (PAN), has been masked before it is returned to your application. This default behavior prevents your application being pulled in PCI DSS scope, since it only comes in touch with a truncated portion of the cardholder data. Later in this guide we will learn how to [customize masking](#masking).
```

2023-04-18 18:45 UTC, jleon15 commented on docs/guides/collect/collect-cards.mdx
> +### Deduplication
should we add a label for optional steps like (Optional) or something?

2023-04-18 18:47 UTC, jleon15 commented on docs/guides/collect/collect-cards.mdx
> +Companies often find it necessary to uniquely identify cards flowing through their systems for various reasons, which may include: preventing fraudulent transactions, detecting abuse of credit cards,
```suggestion
Companies often find it necessary to uniquely identify cards flowing through their systems for various reasons, which may include: preventing fraudulent transactions, detecting credit cards abuse, building consumer profiles or streamlining payment processing for a better user experience.
```

2023-04-18 18:48 UTC, jleon15 commented on docs/guides/collect/collect-cards.mdx
> +By leveraging [token fingerprinting](/docs/concepts/what-are-tokens#fingerprinting), developers can recognize the tokenized data in a customizable fashion, without having to come in contact with the
```suggestion
By leveraging [token fingerprinting](/docs/concepts/what-are-tokens#fingerprinting), developers can recognize the tokenized data in a customizable fashion, without having to touch the plaintext data. For cards, it is common to index the Primary Account Number (PAN). In some cases the expiration date may also be considered.
```

2023-04-18 18:54 UTC, jleon15 commented on docs/guides/collect/collect-cards.mdx
> +In the example above, we instruct Basis Theory to reveal both segments, without having to worry about the card brand or number length. [Click here to learn more about Masking](/docs/expressions/masks
I think we should either not reveal both as the example or add a warning that this means for a 16 digit card, only 4 digits are masked which would make it easy to brute force the actual number

2023-04-18 18:55 UTC, jleon15 commented on docs/guides/collect/collect-cards.mdx
> +In the example below, we will pass a predefined token `id` that follows a custom logic, which resembles an alternative format used in the payments industry:
```suggestion
In the example below, we will pass a predefined token `id` that follows custom logic, which resembles an alternative format used in the payments industry:
```

2023-04-18 18:56 UTC, jleon15 commented on docs/guides/collect/collect-cards.mdx
> +While storing or transmitting tokens between systems, you may encounter restrictive technical constraints that can draw the default token Universally Unique Identifier (UUID) incompatible.
```suggestion
While storing or sharing tokens between systems, you may encounter restrictive technical constraints that can draw the default token Universally Unique Identifier (UUID) incompatible.
```

2023-04-18 18:58 UTC, jleon15 commented on docs/guides/collect/collect-cards.mdx
> +function generateTokenId() {
this example id feels weird, i would actually use an alias filter instead

2023-04-18 18:59 UTC, jleon15 commented on docs/guides/collect/collect-cards.mdx
> +The best practices prescribed in this guide ensure that your user-facing applications are compliant with the PCI-DSS standards and your users' sensitive card data is protected. The `token.id` obtaine
```suggestion
The best practices prescribed in this guide ensure that your user-facing applications are compliant with the PCI-DSS standards and your users' sensitive card data is protected. The `token.id` obtained at the end of the [Storing Cards](#storing-cards) section is a synthetic replacement for the sensitive data and can be safely stored in your database, or shared through your systems, meeting compliance requirements and reducing the risk of exposure in case of data breaches.
```

2023-04-18 18:59 UTC, jleon15 commented on docs/guides/collect/collect-cards.mdx
> +The optional [customization steps](#customizing-tokens) are meant for showcase platform capabilities that go beyond the examples given. Make sure to explore the provided links within each subsection
```suggestion
The optional [customization steps](#customizing-tokens) are meant to showcase platform capabilities that go beyond the examples given. Make sure to explore the provided links within each subsection to learn more about the possibilities for customization.
```

2023-04-18 19:03 UTC, jleon15 commented on docs/guides/collect/collect-cards.mdx
> +The steps so far cover most cases when you need to collect cards in your frontend and store them in a secure location. However, in some scenarios you may need to customize your card tokens for specif
It would be cool if we could collapse all the optional sections

2023-04-19 10:52 UTC, armsteadj1 submitted a review, later dismissed

2023-04-19 12:46 UTC, djejaquino commented on docs/guides/collect/collect-cards.mdx
> +### Deduplication
Let's try to find a pattern in next few guides.

2023-04-19 12:53 UTC, djejaquino commented on docs/guides/collect/collect-cards.mdx
> +In the example below, we will pass a predefined token `id` that follows a custom logic, which resembles an alternative format used in the payments industry:
I believe "which" makes "a" required in this case.

2023-04-19 12:53 UTC, djejaquino commented on docs/guides/collect/collect-cards.mdx
> +function generateTokenId() {
It is common practice, specially for Token Portability.

2023-04-19 12:53 UTC, djejaquino commented on docs/guides/collect/collect-cards.mdx
> +function generateTokenId() {
I will state that.

2023-04-19 12:56 UTC, djejaquino commented on docs/guides/collect/collect-cards.mdx
> +The best practices prescribed in this guide ensure that your user-facing applications are compliant with the PCI-DSS standards and your users' sensitive card data is protected. The `token.id` obtaine
"Transmitted" is the right term here to invoke internal use of tokens.

2023-04-19 12:57 UTC, djejaquino commented on docs/guides/collect/collect-cards.mdx
> +The steps so far cover most cases when you need to collect cards in your frontend and store them in a secure location. However, in some scenarios you may need to customize your card tokens for specif
Agree. Ruled out of scope in this one.

2023-04-19 13:00 UTC, armsteadj1 approved these changes

2023-04-19 13:28 UTC, merged