feat: documenting alias_card filter
Basis-Theory/developers.basistheory.com pull request #119
Opened 2023-05-12 21:29 UTC by jleon15

## Description

- Document alias_card filter

## Testing required outside of automated testing?

- [x] Not Applicable

### Screenshots (if appropriate):

- [x] Not Applicable

## Rollback / Rollforward Procedure

- [x] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2023-05-12 21:32 UTC, jleon15 commented on docs/expressions/filters.mdx
> +| <code>{{ data &#124; alias_card }}</code>              | `"3292-2312-4920-2291"` |
i wonder if we should use `card_number` type instead as that's what i would recommend if tokenizing card numbers, but then we cannot demonstrate the examples preserving the delimiters as only generic tokens can contain spaces or dashes in the card number

2023-05-15 12:45 UTC, djejaquino requested changes

2023-05-15 12:45 UTC, djejaquino commented on docs/expressions/filters.mdx
> +| <code>{{ data &#124; alias_card }}</code>              | `"3292-2312-4920-2291"` |
Yes. We should demonstrate usage with both `card` (`{{data.number | alias_card }}`)  and `card_number`

2023-05-15 12:45 UTC, djejaquino commented on docs/expressions/filters.mdx
> +## card_mask
Same thing for this filter.

2023-05-15 14:42 UTC, jleon15 commented on docs/expressions/filters.mdx
> +| <code>{{ data &#124; alias_card }}</code>              | `"3292-2312-4920-2291"` |
right now the example is using token type `token`, I wouldn't want to add 3 examples for each, so maybe just 1 more, either `card` or `card_number`

2023-05-17 15:13 UTC, merged

2023-05-17 15:14 UTC, bt-platform-eng commented
:tada: This PR is included in version 1.47.0 :tada:

The release is available on [GitHub release](https://github.com/Basis-Theory/developers.basistheory.com/releases/tag/v1.47.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: