Add "Display Cards" Guide
Basis-Theory/developers.basistheory.com pull request #134
Opened 2023-06-07 12:53 UTC by djejaquino

## Description

Title

## Testing required outside of automated testing?

- [ ] Not Applicable

### Screenshots (if appropriate):

- [ ] Not Applicable

## Rollback / Rollforward Procedure

- [ ] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2023-06-08 18:38 UTC, kevinperaza commented on docs/guides/collect/collect-cards-single-element.mdx
> +Once installed and configured, add the Card Element to your application. This will enable your users to type in their card data in your form, while ensuring your systems never come in contact with th
```
Once installed and configured, add the Card Element to your application; it will enable your users to type in their card data in your form while ensuring your systems never come in contact with the data.
```

2023-06-09 17:54 UTC, brigonzalez commented on docs/guides/share/display-cards.mdx
> +            let nonce = data!.nonce!
the Swift stuff looks good. the only comment I have about it is that to pull the sessionKey and nonce out of this, you'd have to set it to some private var set in this class. like we do with sessionKey here https://github.com/Basis-Theory/basistheory-ios/blob/master/IntegrationTester/UnitTests/GetTokenByIdServiceTests.swift#L37

2023-06-09 17:59 UTC, brigonzalez commented on docs/guides/share/display-cards.mdx
> +  http.Handle("/", http.FileServer(http.Dir("public")))
```suggestion
```
I think you can get rid of this line

2023-06-09 19:13 UTC, lcschy commented on docs/guides/share/display-cards.mdx
> +```
Missing this to actually start the express app:

```javascript
app.listen(port, () => {
  console.log(`Server listening on port ${port}`);
});
```

2023-06-09 19:14 UTC, lcschy commented on docs/guides/share/display-cards.mdx
> +from flask import Flask, redirect, request
```suggestion
from flask import Flask, request
```

2023-06-09 19:14 UTC, lcschy commented on docs/guides/share/display-cards.mdx
> +    authorizedSession = session_client.authorize(authorize_session_request=AuthorizeSessionRequest(
```suggestion
session_client.authorize(authorize_session_request=AuthorizeSessionRequest(
```

2023-06-09 20:50 UTC, jleon15 commented on docs/guides/share/display-cards.mdx
> +  Be sure to replace <code>test_1234567890</code> with the Public API Key you created previously.
this alert should appear later as there is no api key being used yet

2023-06-09 20:51 UTC, jleon15 commented on docs/guides/share/display-cards.mdx
> +  Be sure to replace <code>test_1234567890</code> with the Public API Key you created previously.
oh it is duplicated, just get rid of the first one

2023-06-09 20:57 UTC, jleon15 commented on docs/guides/share/display-cards.mdx
> +      val url = URL("http://localhost:4242/authorize")
I don't think this compiles

2023-06-09 20:58 UTC, jleon15 commented on docs/guides/share/display-cards.mdx
> +      val url = URL("http://localhost:4242/authorize")
it needs to be new URL(...)

2023-06-09 21:01 UTC, jleon15 commented on docs/guides/share/display-cards.mdx
> +      val url = URL("http://localhost:4242/authorize")
I would prefer using okhttp3 instead of the URL library

2023-06-09 21:05 UTC, jleon15 commented on docs/guides/share/display-cards.mdx
> +Now let's have our frontend `display` function call this new endpoint passing the session `nonce`.
should you add another alert for the api key in here? or maybe just do a global alert for all?

2023-06-09 21:08 UTC, jleon15 commented on docs/guides/share/display-cards.mdx
> +<Tabs className="bt-tabs" queryString="frontend">
same here with the api key

2023-06-09 21:09 UTC, jleon15 commented on docs/guides/share/display-cards.mdx
> +      cardNumberElement.setValueRef(token.data.number)
you need to do this cardNumberElement.setValueRef(token.data.getElementValueReference("number")) for all of them

2023-06-09 21:13 UTC, jleon15 commented on docs/guides/collect/collect-cards-single-element.mdx
> +# Collect Cards (Single Element)
It feels weird not having this on the sidebar

2023-06-09 21:15 UTC, jleon15 requested changes
Nice guides! left a few comments

2023-06-09 23:40 UTC, kevinperaza commented on docs/guides/share/display-cards.mdx
> +```
also adding these may be helpful for a broader range of skillsets

```js
const cors = require("cors");
...
app.use(cors());
app.use(express.json());
```

2023-06-10 00:00 UTC, kevinperaza commented on docs/guides/share/display-cards.mdx
> +If you don't have yet cards stored with Basis Theory, here are a few guides you can explore:
Should we be more thorough about having some test data before starting with this guide? Adding an alert or rephrasing this sentence may make it easier for people just jumping into the BT world with little context on collecting card data with our products.

2023-06-12 12:10 UTC, djejaquino commented on docs/guides/collect/collect-cards-single-element.mdx
> +# Collect Cards (Single Element)
It kinda does. It feels worst having it though. When we reorganize the docs I will find a place for this.

2023-06-12 12:12 UTC, djejaquino commented on docs/guides/collect/collect-cards-single-element.mdx
> +Once installed and configured, add the Card Element to your application. This will enable your users to type in their card data in your form, while ensuring your systems never come in contact with th
;

2023-06-12 13:57 UTC, djejaquino commented on docs/guides/share/display-cards.mdx
> +If you don't have yet cards stored with Basis Theory, here are a few guides you can explore:
I think this is a good idea. Do you have a suggestion for rephrasing this?

2023-06-12 14:11 UTC, djejaquino commented on docs/guides/share/display-cards.mdx
> +Now let's have our frontend `display` function call this new endpoint passing the session `nonce`.
This is the backend, and the private key alert is there, a few lines above.

2023-06-12 14:19 UTC, djejaquino commented on docs/guides/share/display-cards.mdx
> +      val url = URL("http://localhost:4242/authorize")
If you think it is valuable, please go ahead and make the changes. I just copied this implementation from another guide because I don't have much expertise

2023-06-12 14:20 UTC, djejaquino commented on docs/guides/share/display-cards.mdx
> +<Tabs className="bt-tabs" queryString="frontend">
What do you mean?

2023-06-12 14:23 UTC, djejaquino commented on docs/guides/share/display-cards.mdx
> +      cardNumberElement.setValueRef(token.data.number)
Same as for the Proxy?
https://github.com/Basis-Theory/basistheory-android/blob/master/example/src/main/java/com/basistheory/android/example/view/reveal/RevealDataFragment.kt

2023-06-12 15:09 UTC, kevinperaza commented on docs/guides/share/display-cards.mdx
> +If you don't have yet cards stored with Basis Theory, here are a few guides you can explore:
Maybe something along the lines of

```
Unlock a seamless experience with Basis Theory by **ensuring you have test data readily available before diving into this guide**. Don't worry if you're new to collecting card data with our products – we've got you covered! Explore our comprehensive introductory guides to start and hit the ground running in no time: 
```
?

2023-06-12 15:41 UTC, djejaquino commented on docs/guides/share/display-cards.mdx
> +If you don't have yet cards stored with Basis Theory, here are a few guides you can explore:
Yes. Done.

2023-06-12 20:15 UTC, jleon15 commented on docs/guides/share/display-cards.mdx
> +      val url = URL("http://localhost:4242/authorize")
which other guide uses this?

2023-06-12 20:16 UTC, jleon15 commented on docs/guides/share/display-cards.mdx
> +      cardNumberElement.setValueRef(token.data.number)
yes

2023-06-12 20:39 UTC, djejaquino commented on docs/guides/share/display-cards.mdx
> +      val url = URL("http://localhost:4242/authorize")
https://developers.basistheory.com/docs/guides/share/reveal-tokenized-data#calling-the-authorization-endpoint

https://developers.basistheory.com/docs/guides/share/reveal-data-from-third-party#calling-the-authorization-endpoint

2023-06-12 20:43 UTC, djejaquino commented on docs/guides/share/display-cards.mdx
> +<Tabs className="bt-tabs" queryString="frontend">
Yea. There are two public api key alerts, because how SDKs require it at different moments. And one private API alert after the backend implementation.

2023-06-12 20:51 UTC, jleon15 commented on docs/guides/share/display-cards.mdx
> +      val url = URL("http://localhost:4242/authorize")
Interesting, we should update it eventually

2023-06-12 20:51 UTC, jleon15 approved these changes

2023-06-12 20:52 UTC, merged

2023-06-12 20:56 UTC, bt-platform-eng commented
:tada: This PR is included in version 1.56.0 :tada:

The release is available on [GitHub release](https://github.com/Basis-Theory/developers.basistheory.com/releases/tag/v1.56.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: