feat: adds iOS collect guide
Basis-Theory/developers.basistheory.com pull request #18
Opened 2023-01-03 15:04 UTC by brigonzalez

## Description

- adds iOS collect guide

## Testing required outside of automated testing?

- [x] Not Applicable

### Screenshots (if appropriate):

- will add screenshots in a bit

## Rollback / Rollforward Procedure

- [x] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2023-01-03 21:57 UTC, lcschy approved these changes

2023-01-04 15:46 UTC, bweber requested changes

2023-01-04 15:46 UTC, bweber commented on docs/guides/collect/collect-data-with-ios.mdx
> +With the Xcode window in focus, select File > Add Packages. In the dialog that appears, enter "https://github.com/Basis-Theory/basistheory-ios" in the search field on the top right, then click Add Pa
`"https://github.com/Basis-Theory/basistheory-ios"` is creating a weird link in the guide.

2023-01-04 15:46 UTC, bweber commented on docs/guides/collect/collect-data-with-ios.mdx
> +With the new `UITextField` selected, open up the Identity Inspector on the right and select "TextElementUITextField" from the class drop down, similar to the image below.
```suggestion
With the new `UITextField` selected, open up the Identity Inspector on the right and select `TextElementUITextField` from the class drop down, similar to the image below.
```

2023-01-04 15:46 UTC, bweber commented on docs/guides/collect/collect-data-with-ios.mdx
> +With the Xcode window in focus, select File > Add Packages. In the dialog that appears, enter "https://github.com/Basis-Theory/basistheory-ios" in the search field on the top right, then click Add Pa
```suggestion
With the Xcode window in focus, select File > Add Packages. In the dialog that appears, enter `https://github.com/Basis-Theory/basistheory-ios` in the search field on the top right, then click Add Package on this screen and the next prompts.
```

2023-01-04 15:46 UTC, bweber commented on docs/guides/collect/collect-data-with-ios.mdx
> +//
Remove these comments for your examples.

2023-01-04 15:46 UTC, bweber commented on docs/guides/collect/collect-data-with-ios.mdx
> +//
Remove these comments for your examples.

2023-01-04 15:46 UTC, bweber commented on docs/guides/collect/collect-data-with-ios.mdx
> +//
Remove these comments for your examples.

2023-01-04 15:46 UTC, bweber commented on docs/guides/collect/collect-data-with-ios.mdx
> +//
Remove these comments for your examples.

2023-01-04 15:46 UTC, bweber commented on docs/guides/collect/collect-data-with-ios.mdx
> +- [Query User Data from an API](/docs/blueprints/personal-information/query-user-data-from-api)
We should send them to a Share guide next instead. Maybe https://developers.basistheory.com/docs/guides/share/send-data-to-third-party

2023-01-04 15:58 UTC, brigonzalez commented on docs/guides/collect/collect-data-with-ios.mdx
> +- [Query User Data from an API](/docs/blueprints/personal-information/query-user-data-from-api)
lol sure. the choices here seemed random to me

2023-01-04 16:30 UTC, merged

2023-01-04 16:31 UTC, bt-platform-eng commented
:tada: This PR is included in version 1.4.0 :tada:

The release is available on [GitHub release](https://github.com/Basis-Theory/developers.basistheory.com/releases/tag/v1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: