se-219 feat: Review mentions of digits length for expiration_month and expiration_year
Basis-Theory/developers.basistheory.com pull request #437
Opened 2024-08-21 18:11 UTC by adrielfsc

## Description

-

## Testing required outside of automated testing?

- [ ] Not Applicable

### Screenshots (if appropriate):

- [ ] Not Applicable

## Rollback / Rollforward Procedure

- [ ] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2024-08-21 18:53 UTC, djejaquino requested changes

2024-08-21 18:53 UTC, djejaquino commented on docs/api/orchestration/stripe-forward.mdx
> +| `exp_month`        | false    | _string_ | `null`  | String representing the card's expiration month                      |
Since this is a String, we should keep it as it is.

```suggestion
| `exp_month`        | false    | _string_ | `null`  | Two-digit string representing the card's expiration month                      |
```

2024-08-21 18:53 UTC, djejaquino commented on docs/api/orchestration/stripe-forward.mdx
> +| `exp_year`         | false    | _string_ | `null`  | String representing the card's expiration year                       |
Same thing here.

2024-08-21 18:53 UTC, djejaquino commented on docs/sdks/mobile/android/types.mdx
> +  | `month(): ElementValueReference`                                             | Returns a value reference to the number representing the card's expiration month.                  |
Double-check if the Android SDK returns a String or Number. We should make the type explicit here.
If it is a String, we need to keep the description.

2024-08-22 14:42 UTC, adrielfsc commented on docs/sdks/mobile/android/types.mdx
> +  | `month(): ElementValueReference`                                             | Returns a value reference to the number representing the card's expiration month.                  |
yes, it's an int

2024-08-22 14:50 UTC, djejaquino approved these changes

2024-08-22 17:43 UTC, merged

2024-08-23 11:49 UTC, bt-platform-eng commented
:tada: This issue has been resolved in version 1.173.0 :tada:

The release is available on [GitHub release](https://github.com/Basis-Theory/developers.basistheory.com/releases/tag/v1.173.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: