feat: Adds async reactor documentation
Basis-Theory/developers.basistheory.com pull request #76
Opened 2023-02-16 20:34 UTC by dhudec

## Description

- Documents async reactors
- Documents reactor errors and the reactor formula JS SDK

## Testing required outside of automated testing?

- [x] Not Applicable

### Screenshots (if appropriate):

- [x] Not Applicable

## Rollback / Rollforward Procedure

- [x] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2023-02-16 21:39 UTC, dhudec commented on docs/concepts/what-are-reactors.mdx
> +## Asynchronous Reactors
```suggestion
### Asynchronous Reactors
```

2023-02-17 18:00 UTC, jleon15 commented on docs/api/reactors/reactor-errors.mdx
> +      case 'StripeAPIError':
are these cases needed? it would go to the default case anyway

2023-02-17 18:01 UTC, jleon15 commented on docs/api/reactors/reactors.mdx
> +| `callback_url` | false    | _string_ | `null`  | Indicates that the reactor should be invoked asynchronously and the result delivered as a webhook to this url. See [Asynchronous Reactors](/docs/con
```suggestion
| `callback_url` | false    | _string_ | `null`  | Indicates that the reactor should be invoked asynchronously and the result delivered as a webhook to this URL. See [Asynchronous Reactors](/docs/concepts/what-are-reactors#asynchronous-reactors) for more info.                                                |
```

2023-02-17 18:02 UTC, jleon15 commented on docs/api/reactors/reactors.mdx
> +| `timeout_ms`   | false    | _int_    | `10000` | The maximum execution time for the reactor. Value must be between `10000` (10s) and `210000` (3.5m). Only supported for [Asynchronous Reactor](/docs
```suggestion
| `timeout_ms`   | false    | _int_    | `10000` | The maximum execution time for the reactor. Value must be between `10000` (10s) and `210000` (3.5m). Only supported for [Asynchronous Reactors](/docs/concepts/what-are-reactors#asynchronous-reactors) requests.                                                 |
```

2023-02-17 18:06 UTC, jleon15 commented on docs/concepts/what-are-reactors.mdx
> +respond with a `2xx` status code, delivery will retried up to 10 times with exponential backoff.
should we specify what this exponential backoff is?

2023-02-17 18:06 UTC, jleon15 commented on docs/concepts/what-are-reactors.mdx
> +respond with a `2xx` status code, delivery will retried up to 10 times with exponential backoff.
or maybe just provide the range it could be within

2023-02-17 18:25 UTC, dhudec commented on docs/api/reactors/reactor-errors.mdx
> +      case 'StripeAPIError':
I suppose they aren't. I copied this from our official stripe reactor

2023-02-17 19:34 UTC, dhudec commented on docs/concepts/what-are-reactors.mdx
> +respond with a `2xx` status code, delivery will retried up to 10 times with exponential backoff.
> delivery will retried up to 10 times with exponential backoff over the next ~2.5 hours

2023-02-21 15:18 UTC, armsteadj1 requested changes

2023-02-21 15:18 UTC, armsteadj1 commented on docs/api/reactors/reactor-errors.mdx
> +Some vendors express error scenarios via HTTP status codes, while others opt to return a generic status code such as `200 OK` while
```suggestion
Some external APIs express error scenarios via HTTP status codes, while others opt to return a generic status code such as `200 OK` while
```

2023-02-21 15:18 UTC, armsteadj1 commented on docs/api/reactors/reactor-errors.mdx
> +Some vendors express error scenarios via HTTP status codes, while others opt to return a generic status code such as `200 OK` while
@dhudec I actually wonder if this is fine now that i read everything. I've been trying to think about how I talk about these relationships vs how one of our end-users may. 

Vendor may be fine now, although I'm wondering if we should be talking about it specifically as an API vs Vendor/3rd Party in our docs as that is really what they would be interacting with. 

Thoughts? (for now I'm fine if you close this without adding it and we can talk more in Slack)

2023-02-21 15:18 UTC, armsteadj1 commented on docs/api/reactors/reactors.mdx
> +| `args`         | false    | _object_ | `null`  | Arguments to provide to the reactor. These arguments must contain the declared [request parameters](/docs/api/reactors/reactor-formulas#reactor-form
Is this still true? i thought we did away with "required" arguments?

Or does this mean that IF the reactor defines them, you MUST include them?

2023-02-21 15:18 UTC, armsteadj1 commented on docs/api/reactors/reactors.mdx
> +| `args`         | false    | _object_ | `null`  | Arguments to provide to the reactor. These arguments must contain the declared [request parameters](/docs/api/reactors/reactor-formulas#reactor-form
if the latter, we should be explicit about that here. I can suggest if that's the case.

2023-02-21 15:18 UTC, armsteadj1 commented on docs/api/reactors/reactors.mdx
> +| `timeout_ms`   | false    | _int_    | `10000` | The maximum execution time for the reactor. Value must be between `10000` (10s) and `210000` (3.5m). Only supported for [Asynchronous Reactors](/doc
the value CANT be less than 10s?

2023-02-21 15:18 UTC, armsteadj1 commented on docs/concepts/what-are-reactors.mdx
> +Reactors can be invoked asynchronously by providing a `callback_url` parameter within the [request](/docs/api/reactors#invoke-a-reactor).
```suggestion
Reactors are invoked asynchronously by providing a `callback_url` parameter within the [request](/docs/api/reactors#invoke-a-reactor).
```

2023-02-21 15:32 UTC, dhudec commented on docs/api/reactors/reactors.mdx
> +| `timeout_ms`   | false    | _int_    | `10000` | The maximum execution time for the reactor. Value must be between `10000` (10s) and `210000` (3.5m). Only supported for [Asynchronous Reactors](/doc
the way it is right now, that's correct...

2023-02-21 15:49 UTC, dhudec commented on docs/api/reactors/reactors.mdx
> +| `args`         | false    | _object_ | `null`  | Arguments to provide to the reactor. These arguments must contain the declared [request parameters](/docs/api/reactors/reactor-formulas#reactor-form
Good catch, we don't require request parameters to be declared anymore

2023-02-21 17:00 UTC, armsteadj1 approved these changes

2023-02-21 17:02 UTC, merged

2023-02-21 17:03 UTC, bt-platform-eng commented
:tada: This PR is included in version 1.32.0 :tada:

The release is available on [GitHub release](https://github.com/Basis-Theory/developers.basistheory.com/releases/tag/v1.32.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: