feat: add Extract Data guide
Basis-Theory/developers.basistheory.com pull request #82
Opened 2023-02-20 19:20 UTC by djejaquino

## Description

-

## Testing required outside of automated testing?

- [ ] Not Applicable

### Screenshots (if appropriate):

- [ ] Not Applicable

## Rollback / Rollforward Procedure

- [ ] Roll Forward
- [ ] Roll Back

## Reviewer Checklist

- [ ] Description of Change
- [ ] Description of outside testing if applicable.
- [ ] Description of Roll Forward / Backward Procedure
- [ ] Documentation updated for Change

2023-02-21 21:03 UTC, armsteadj1 requested changes

2023-02-21 21:03 UTC, armsteadj1 commented on docs/guides/process/extract-data.mdx
> +# Extract Data
```suggestion
# Extract OCR Data
```

I wonder if we should be more specific about what this is doing?

2023-02-22 12:08 UTC, djejaquino commented on docs/guides/process/extract-data.mdx
> +# Extract Data
Fair enough

2023-02-23 14:43 UTC, armsteadj1 requested changes

2023-02-23 14:43 UTC, armsteadj1 commented on docs/guides/process/extract-data.mdx
> +# Extract OCR Data
```suggestion
# Extract Data
```

2023-02-23 15:07 UTC, armsteadj1 approved these changes

2023-02-23 15:42 UTC, merged

2023-02-23 15:43 UTC, bt-platform-eng commented
:tada: This PR is included in version 1.33.0 :tada:

The release is available on [GitHub release](https://github.com/Basis-Theory/developers.basistheory.com/releases/tag/v1.33.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: